packages:
  - packages/*
  - plugins/*
  - docs
  - build

catalog:
  vue: ^3.5.13
  vite: ^6.0.7
  vitepress: ^1.6.3
  sass: ^1.83.1
  js-yaml: ^4.1.0
  picocolors: ^1.1.1
  tinyglobby: ^0.2.10
  gray-matter: ^4.0.3
  markdown-it-container: ^4.0.0
  "@iconify/vue": ^4.3.0
  "@types/js-yaml": ^4.0.9
  "@types/markdown-it": ^14.1.2
  "@types/markdown-it-container": ^2.0.10
  vitepress-plugin-auto-frontmatter: ^1.0.10
  vitepress-plugin-catalogue: ^1.0.15
  vitepress-plugin-doc-analysis: ^1.0.12
  vitepress-plugin-file-content-loader: ^1.0.12
  vitepress-plugin-md-h1: ^1.0.11
  vitepress-plugin-permalink: ^1.1.2
  vitepress-plugin-sidebar-resolve: ^1.0.10

catalogs:
  vue:
    '@vue/compiler-core': ^3.5.13
    '@vue/compiler-dom': ^3.5.13
    '@vue/reactivity': ^3.5.13
    '@vue/runtime-core': ^3.5.13
    '@vue/runtime-dom': ^3.5.13